.TH GEDIT 1 "24 Apr 2006"
.SH NAME
\fBgedit\fP \- text editor for the MATE Desktop

.SH SYNOPSIS
.B gedit
[\fIOPTION\fR]... [\fIFILE\fR]...
.SH DESCRIPTION
.B gedit
is the official text editor of the MATE desktop environment.

While aiming at simplicity and ease of use,
.B gedit
is a powerful general purpose text editor.
It can be used to create and edit all kinds of text files.

.B gedit
features a flexible plugin system which can be used to dynamically add 
new advanced features to
.B gedit
itself.
.LP
.SH OPTIONS

.TP
\fB\-\-help\fR
Prints the command line options.
.TP
\fB\-\-encoding\fR
Set the character encoding to be used for opening the files listed on the command line".
.TP
\fB\-\-new\-window\fR
Create a new toplevel window in an existing instance of
.B gedit.
.TP
\fB\-\-new\-document\fR
Create a new document in an existing instance of
.B gedit.
.TP
\fB+[num]\fR
For the first file, go to the line specified by "num" (do not insert a space between the "+" sign and the number).
If "num" is missing, go to the last line.
.TP
\fBfilename(s)...\fR
Specifies the file to open when 
.B gedit
starts. If this is not specified, 
.B gedit
will load a blank file with an "Unsaved Document" label. Multiple files can be loaded if they are
separated by spaces.  
.B gedit
also supports handling of remote files.  For example, you can pass the location 
of a webpage to
.B gedit,
like "http://www.mate.org", or load a file from a FTP server,
like "ftp://ftp.mate.org/robots.txt".
.TP
\fB\-\-list-encodings\fR
Display list of possible values for the encoding option and exit
.TP
\fB\-\-version\fR
Output version information and exit

.SH BUGS
If you find a bug, please report it at http://bugzilla.mate.org/enter_bug.cgi?product=gedit.
.SH AUTHORS
Paolo Maggi (paolo@gnome.org)
.TP
Paolo Borelli (pborelli@katamail.com)
.TP
James Willcox (jwillcox@gnome.org)
.TP
Federico Mena Quintero (federico@novell.com)
.TP
Chema Celorio

