.\" Man page for Xedit.
.TH XEDIT 1
.\"
.SH "NAME"
Xedit \- The Text Editor
.SH "SYNOPSIS"
.B xedit [OPTIONS...] [FILES...]
.SH "DESCRIPTION"
Xedit is the official text editor of the X-APPS project, which aims to provide applications to the Cinnamon, MATE and Xfce desktops. While aiming at simplicity and ease of use, Xedit is a powerful general purpose text editor. It can be used to create and edit all sorts of text files.
.PP
Xedit features a flexible plugin system which can be used to dynamically add new advanced features to Xedit itself.
.PP
This manual page briefly documents the \fBxedit\fR command.

.SH "OPTIONS"
.TP
\fBfilename(s)...\fR
Specifies the file to open when \fBxedit\fR starts. If this is not specified, \fBxedit\fR will start a new, blank file with an "Unsaved Document" label. Multiple files can be loaded if they are separated by spaces. \fBxedit\fR also supports handling of remote files.
.TP
\fB\-\-display=DISPLAY\fR
X display to use.
.TP
\fB\-\-encoding\fR
Set the character encoding to be used for opening the files listed on the command line.
.TP
\fB\-\-new\-window\fR
Create a new toplevel window in an existing instance of \fBxedit\fR.
.TP
\fB\-\-new\-document\fR
Create a new document in an existing instance of \fBxedit\fR, on the last Xedit window that had focus.
.TP
\fB+[num]\fR
For the first file, go to the line specified by "num" (do not insert a space between the "+" sign and the number).
If "num" is missing, go to the last line.
.TP
\fB\-\-list-encodings\fR
Display list of possible values for the encoding option and exit
.TP
\fB\-\-version\fR
Output version information and exit
.TP
\fB\-?, \-h, \-\-help\fR
Print standard command line options.
.TP
\fB\-\-help\-all\fR
Print all command line options.
.P
This program also accepts the standard GTK options.

.SH "EXAMPLES"
\fBxedit \-\-encoding WINDOWS-1252 ftp://ftp.kernel.org/pub/linux/kernel/README\fR
.RS 4
Open the Linux Kernel README file from kernel.org's FTP server using Windows-1252 character encoding.
.RE
.PP
\fBxedit +156 http://www.some-website.com/\fR
.RS 4
Open the main web page of some-website.com and jump to line 156.
.RE
.PP
\fBxedit \-\-new\-window ~/.bashrc ~/.bash_history\fR
.RS 4
Open the current users .bashrc and .bash_history files in a new window.

.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/linuxmint/xedit/issues

.fi
.SH "SEE ALSO"
.SS
Xedit documentation can be found from the "Help" menu, or by pressing the F1 key. 
